# Generated by Django 5.0.2 on 2024-02-22 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediapost',
            name='user',
        ),
    ]
