# Generated by Django 5.0.2 on 2024-02-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_socialmediapost_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_posts', models.IntegerField(default=0)),
                ('total_likes', models.IntegerField(default=0)),
                ('total_comments', models.IntegerField(default=0)),
                ('total_shares', models.IntegerField(default=0)),
            ],
        ),
    ]
