# Generated by Django 5.0.2 on 2024-02-22 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_dashboardstatistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediapost',
            name='scheduled_time',
        ),
    ]
